spring:
  application:
    name: apollo-adminservice
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: root
server:
  port: 8090
logging:
  file: /opt/logs/apollo/apollo-adminservice.log
