spring:
  application:
    name: apollo-configservice
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: root
logging:
  file: /var/log/apollo/apollo-configservice.log
