spring:
  application:
    name: apollo-configservice
  datasource:
    url: jdbc:mysql://service-mysql-for-apollo.sre:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: root
logging:
  file: /opt/logs/apollo/apollo-configservice.log
