spring:
  application:
    name: apollo-portal
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ApolloPortalDB?characterEncoding=utf8
    username: root
    password: root
server:
  port: 8070
  compression:
    enabled: true
  
logging:
  file: /opt/logs/apollo/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP

apollo:
  config-service-url:
    dev: http://localhost:8080
  admin-service-url:
    dev: http://localhost:8090
