spring:
  application:
    name: apollo-portal
  datasource:
    url: jdbc:mysql://service-mysql-for-apollo.sre:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: root
server:
  port: 8070
  compression:
    enabled: true
  
logging:
  file: /opt/logs/apollo/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 
